### ISSUE TITLE
Probable issue on 'z' token for january dates

### ISSUE THREAD

**Issue by ericmorand** [crocodile2u/js-date-format#1]
Here is the `z` token function:

`return year.slice(0, d.getMonth()).reduce((a, b) => a + b) + d.getDate() - 1;`

I think that reduce will fail when` d.getMonth()` returns 0 - i.e. january. An initial value is mandatory when the array to reduce is empty:

`return year.slice(0, d.getMonth()).reduce((a, b) => a + b, 0) + d.getDate() - 1;
`

**Comment by ericmorand** [comment]
I

**Comment by crocodile2u** [comment]
thanks, will take a look

**Comment by crocodile2u** [comment]
Fixed in 1.0.6
